# Generated by Django 4.2.6 on 2023-10-19 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
